from __future__ import annotations

import argparse
import re
import unicodedata
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

DEFAULT_OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "vocalbin"
    / "cartesia"
    / "generated"
    / "voices.py"
)


@dataclass(frozen=True)
class VoiceRecord:
    id: str
    name: str


def identifier(name: str) -> str:
    ascii_name = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode()
    result = re.sub(r"[^A-Za-z0-9]+", "_", ascii_name).strip("_").upper()
    if not result:
        return "VOICE"
    if result[0].isdigit():
        return f"VOICE_{result}"
    return result


def enum_members(voices: Iterable[VoiceRecord]) -> list[tuple[str, str]]:
    records = sorted({voice.id: voice for voice in voices}.values(), key=_sort_key)
    used: set[str] = set()
    members: list[tuple[str, str]] = []

    for voice in records:
        base = identifier(voice.name)
        name = base
        if name in used:
            name = f"{base}_{identifier(voice.id)[:8]}"
        counter = 2
        while name in used:
            name = f"{base}_{identifier(voice.id)[:8]}_{counter}"
            counter += 1
        used.add(name)
        members.append((name, voice.id))

    return members


def render(voices: Iterable[VoiceRecord]) -> str:
    lines = [
        "# This file is generated by scripts/generate_voices.py.",
        "# Do not edit it manually.",
        "# Run the generator to refresh the Cartesia voice mapping.",
        "from enum import StrEnum",
        "",
        "",
        "class Voice(StrEnum):",
    ]
    members = enum_members(voices)
    if not members:
        lines.append("    pass")
    else:
        lines.extend(f'    {name} = "{voice_id}"' for name, voice_id in members)
    return "\n".join(lines) + "\n"


def fetch_public_voices() -> list[VoiceRecord]:
    try:
        from cartesia import Cartesia
    except ImportError as exc:
        raise RuntimeError(
            "Voice generation requires the 'cartesia' extra: "
            "uv run --extra cartesia python scripts/generate_voices.py"
        ) from exc

    from vocalbin.cartesia.credentials import Credentials

    api_key = Credentials().api_key.get_secret_value()
    with Cartesia(api_key=api_key) as client:
        return [
            VoiceRecord(id=voice.id, name=voice.name)
            for voice in client.voices.list(is_owner=False, limit=100)
            if voice.is_public and not voice.is_owner
        ]


def write_voices(voices: Iterable[VoiceRecord], output: Path) -> bool:
    content = render(voices)
    if output.exists() and output.read_text(encoding="utf-8") == content:
        return False
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8", newline="\n")
    return True


def _sort_key(voice: VoiceRecord) -> tuple[str, str]:
    return voice.name.casefold(), voice.id


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate named Cartesia voice UUID constants."
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    voices = fetch_public_voices()
    changed = write_voices(voices, args.output)
    action = "Updated" if changed else "Already up to date"
    print(f"{action}: {args.output} ({len(voices)} voices)")


if __name__ == "__main__":
    main()
